convert h264 to mp4
Jean-Beru/baby-foot-replay pull request #13
Opened 2018-10-07 16:21 UTC by kevin-verschaeve

it works but it is veeeeeeery slow.

Should try on the rpi, and if too slow, we will need to find something else

2018-10-08 07:43 UTC, Jean-Beru commented
There is nothing to install in Dockerfile ?

2018-10-08 07:45 UTC, kevin-verschaeve commented
There already is ffmpeg, see https://github.com/Jean-Beru/baby-foot-replay/blob/develop/.docker/Dockerfile#L3

but, this install the 3.4.4 version that is not the last, maybe, trying with the 4.0 can be faster

2018-10-08 07:47 UTC, Jean-Beru requested changes

2018-10-08 07:47 UTC, Jean-Beru commented on index.js
> +          console.log('Error: ' + err);
You should also add a `res.statusCode(500).send({ error: err.merssage })`.

2018-10-08 07:47 UTC, Jean-Beru commented on index.js
> +      console.log(arguments);
Same here.

2018-10-08 07:47 UTC, Jean-Beru commented on index.js
> +            if (!error) {
Early return with `if (error) { res.statusCode(500).send({ error: error.merssage }); return; }`

2018-10-08 07:49 UTC, Jean-Beru commented
Correct ! You should test this branch on the rpi to see that (and pray).

2018-10-08 20:11 UTC, Jean-Beru commented on index.js
> +            if (!error) {
Or better (IMO) :
```js
  videoStitch
    .concat({
      silent: !DEBUG,
      overwrite: true,
    })
    .clips(
      videos
        .slice(videos.length - last)
        .map(function(file) {
          return { fileName: `${PUBLIC_FOLDER + LIVE_FOLDER}/${file}` };
        })
    )
    .output(PUBLIC_FOLDER + '/' + tempFile)
    .concat()
    .then(function() {
      return ffmpeg(PUBLIC_FOLDER + '/' + tempFile);
    })
    .then(function(video) {
      video
        .setVideoFormat('mp4')
        .save(PUBLIC_FOLDER + '/' + finalFile, function (error, file) {
          if (error) {
            throw error;
          }

          fs.unlinkSync(PUBLIC_FOLDER + '/' + tempFile);

          res.send(finalFile);
        });
      })
    .catch(function handleError(error) {
      console.log(error);

      res.status(500).send({ error });
    });
```

2018-10-19 11:42 UTC, kevin-verschaeve commented
pr rebased and squashed
useless code removed

do we stay like this or is there anything else to change ?

also, MP4Box is not in the docker image, so this won't work on dev env, should we download and compile it on the Dockerfile ?

2018-10-19 11:48 UTC, Jean-Beru commented
I OK for your changes. Maybe we may factorize convert method (MP4Box or ffmpeg) in a separated module (like `stream/index.js`) but it can be done later.
IMO, we should add MP4Box in Dockerfile. You'll have to use classic image instead of alpine because gpac apk is not available...

2018-10-23 11:24 UTC, Jean-Beru approved these changes

2018-10-23 11:24 UTC, merged